
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD CLOSE_CURL CLOSE_PAR DIV END_ST EQUAL MULT NAME NUMBER OPEN_CURL OPEN_PAR SUBassign : NAME EQUAL expr END_STexpr : expr ADD term \n    | OPEN_PAR expr ADD term CLOSE_PARexpr : expr SUB term \n    | OPEN_PAR expr SUB term CLOSE_PARterm : term MULT factor \n    | OPEN_PAR expr MULT factor CLOSE_PARterm : term DIV factor \n    | OPEN_PAR expr DIV factor CLOSE_PARexpr : term \n       term : factor\n    factor : NUMBER'
    
_lr_action_items = {'NAME':([0,],[2,]),'$end':([1,9,],[0,-1,]),'EQUAL':([2,],[3,]),'OPEN_PAR':([3,6,10,11,16,20,21,],[6,6,16,16,6,16,16,]),'NUMBER':([3,6,10,11,12,13,16,20,21,22,23,],[8,8,8,8,8,8,8,8,8,8,8,]),'END_ST':([4,5,7,8,15,17,18,19,29,30,31,32,],[9,-10,-11,-12,-2,-4,-6,-8,-3,-5,-7,-9,]),'ADD':([4,5,7,8,14,15,17,18,19,24,25,26,29,30,31,32,],[10,-10,-11,-12,20,-2,-4,-6,-8,10,-2,-4,-3,-5,-7,-9,]),'SUB':([4,5,7,8,14,15,17,18,19,24,25,26,29,30,31,32,],[11,-10,-11,-12,21,-2,-4,-6,-8,11,-2,-4,-3,-5,-7,-9,]),'MULT':([5,7,8,14,15,17,18,19,24,25,26,29,30,31,32,],[12,-11,-12,22,12,12,-6,-8,22,12,12,-3,-5,-7,-9,]),'DIV':([5,7,8,14,15,17,18,19,24,25,26,29,30,31,32,],[13,-11,-12,23,13,13,-6,-8,23,13,13,-3,-5,-7,-9,]),'CLOSE_PAR':([7,8,18,19,25,26,27,28,31,32,],[-11,-12,-6,-8,29,30,31,32,-7,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assign':([0,],[1,]),'expr':([3,6,16,],[4,14,24,]),'term':([3,6,10,11,16,20,21,],[5,5,15,17,5,25,26,]),'factor':([3,6,10,11,12,13,16,20,21,22,23,],[7,7,7,7,18,19,7,7,7,27,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assign","S'",1,None,None,None),
  ('assign -> NAME EQUAL expr END_ST','assign',4,'p_assign','test.py',25),
  ('expr -> expr ADD term','expr',3,'p_expr_add','test.py',28),
  ('expr -> OPEN_PAR expr ADD term CLOSE_PAR','expr',5,'p_expr_add','test.py',29),
  ('expr -> expr SUB term','expr',3,'p_expr_sub','test.py',32),
  ('expr -> OPEN_PAR expr SUB term CLOSE_PAR','expr',5,'p_expr_sub','test.py',33),
  ('term -> term MULT factor','term',3,'p_term_mul','test.py',36),
  ('term -> OPEN_PAR expr MULT factor CLOSE_PAR','term',5,'p_term_mul','test.py',37),
  ('term -> term DIV factor','term',3,'p_term_div','test.py',40),
  ('term -> OPEN_PAR expr DIV factor CLOSE_PAR','term',5,'p_term_div','test.py',41),
  ('expr -> term','expr',1,'p_unit','test.py',44),
  ('term -> factor','term',1,'p_unit','test.py',45),
  ('factor -> NUMBER','factor',1,'p_factor','test.py',50),
]
